version: "2.2"
services:
      ws:
        build: .
        ports:
          - 8080:80
        volumes:
          - ./php_rest_demo-main:/var/www/html/rest
      db:
        image: mysql:5.7
        volumes:
          - ./sql:/var/lib/mysql
        ports:
          - 3306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=cicco
      phpadmin:
        image: phpmyadmin:latest
        ports:
          - 8081:80
        environment:
          -   PMA_ARBITRARY=1
